### ISSUE TITLE
v0.0.6中测试labelme_to_coco显示没有mode_list参数

### ISSUE THREAD

**Issue by SWHL** [RapidAI/LabelConvert#9]
#### 使用版本
v0.0.6

#### 报错信息
```
$ python label_convert/labelme_to_coco.py --src_dir dataset/labelme_dataset
Traceback (most recent call last):
  File "/Users//LabelConvert/label_convert/labelme_to_coco.py", line 257, in <module>
    main()
  File "/Users/LabelConvert/label_convert/labelme_to_coco.py", line 253, in main
    converter(mode_list=args.mode_list.split(","))
AttributeError: 'Namespace' object has no attribute 'mode_list'bash
```

**Comment by SWHL** [comment]
已经在`label_convert==0.0.7`中修复
